# Generated by Django 3.1.2 on 2020-10-19 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('landing_page', '0002_delete_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('highlight', models.BooleanField()),
                ('max_peaple', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PlanInclude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable', models.BooleanField()),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing_page.planfeature')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing_page.plan')),
            ],
        ),
    ]
