# Generated by Django 3.1.2 on 2020-10-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0004_plan_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='max_peaple',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
