# Generated by Django 3.1.2 on 2020-10-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0005_auto_20201019_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='max_peaple',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
