# Generated by Django 3.1.2 on 2020-10-19 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0007_auto_20201019_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planinclude',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing_page.planfeature'),
        ),
        migrations.AlterField(
            model_name='planinclude',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='landing_page.plan'),
        ),
    ]
