# Generated by Django 3.1.2 on 2020-10-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0009_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
