# Generated by Django 2.2.12 on 2020-10-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0011_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='price_anual',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
