# Generated by Django 2.2.12 on 2020-10-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0012_plan_price_anual'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
