# Generated by Django 3.1.2 on 2020-11-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0013_feature_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(upload_to='live-static/static/images/team'),
        ),
    ]
