# Generated by Django 3.1.2 on 2020-11-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0014_auto_20201103_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(storage='/home/pepe/Escritorio/Beyl/beyl/live-static/static_root', upload_to='live-static/static/images/team'),
        ),
    ]
