# Generated by Django 3.1.2 on 2020-11-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0016_auto_20201103_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('time_stamp', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
