# Generated by Django 3.1.2 on 2020-11-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0017_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='discount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='founder',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
