# Generated by Django 3.1.2 on 2020-11-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0018_auto_20201122_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
