# Generated by Django 3.1.2 on 2020-11-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0019_plan_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price_anual',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
