# Generated by Django 3.1.2 on 2020-11-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0020_auto_20201122_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='discount',
            field=models.IntegerField(),
        ),
    ]
