# Generated by Django 3.1.2 on 2020-11-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0021_auto_20201122_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('rssc', models.CharField(max_length=200)),
                ('social_media', models.CharField(choices=[('IG', 'Instagram'), ('YT', 'Youtube'), ('TW', 'Twitter'), ('Tk', 'TIK TOK'), ('FC', 'Facebook')], max_length=50)),
            ],
        ),
    ]
