# Generated by Django 3.1.2 on 2020-11-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0022_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='emails',
            name='confirm_privacy',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
