# Generated by Django 3.1.2 on 2020-12-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0023_emails_confirm_privacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='emails',
            name='has_used_other_tool',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
