# Generated by Django 3.1.2 on 2020-12-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0024_emails_has_used_other_tool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emails',
            name='has_used_other_tool',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
