# Generated by Django 3.1.2 on 2020-12-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0026_emails_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emails',
            name='has_used_other_tool',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
